name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    name: stylua & luacheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: stylua --check
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check lua/ plugin/

      - uses: leafo/gh-actions-lua@v13
      - uses: leafo/gh-actions-luarocks@v6

      - name: Install luacheck
        run: luarocks install luacheck

      - name: luacheck
        run: luacheck lua/
